name: Functional Tests

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    # Optional: Early fail if any required env is missing
    - name: Check required environment variables
      run: |
        for var in STANDARD_USER LOCKED_OUT_USER PASSWORD API_KEY; do
          if [ -z "${!var}" ]; then
            echo "$var is not set"
            exit 1
          fi
        done
      env:
        STANDARD_USER: ${{ vars.STANDARD_USER }}
        LOCKED_OUT_USER: ${{ vars.LOCKED_OUT_USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        API_KEY: ${{ secrets.API_KEY }}

    - name: Run tests
      run: npm test
      env:
        STANDARD_USER: ${{ vars.STANDARD_USER }}
        LOCKED_OUT_USER: ${{ vars.LOCKED_OUT_USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        API_KEY: ${{ secrets.API_KEY }}