name: Functional Tests

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
      env:
        STANDARD_USER: ${{ vars.STANDARD_USER }}
        LOCKED_OUT_USER: ${{ vars.LOCKED_OUT_USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        API_KEY: ${{ secrets.API_KEY }}     

    - name: Run tests with --if-present flag
      run: npm test --if-present
      env:
        STANDARD_USER: ${{ vars.STANDARD_USER }}
        LOCKED_OUT_USER: ${{ vars.LOCKED_OUT_USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        API_KEY: ${{ secrets.API_KEY }} 